spring:
  profiles:
    active: test
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:/liquibase/master.xml
  thymeleaf:
    cache: false
    mode: HTML
    check-template: false
  mvc:
    static-path-pattern: /uploads/**
  resources:
    static-locations: /uploads/
server:
  tomcat:
    uri-encoding: UTF-8