logging:
    level:
        ROOT: INFO
        com.noobug: DEBUG
        org.springframework: INFO

spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://119.23.149.25:3306/bxin-web?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: Daedalus@130
        hikari:
            minimum-idle: 5
            maximum-pool-size: 15
            idle-timeout: 300000
            max-lifetime: 1800000
            connection-timeout: 10000
            connection-test-query: SELECT 1
    jpa:
        hibernate:
            ddl-auto: none
        database: MYSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false


server:
    port: 8091